spring:
  application:
    name: challenge
  r2dbc:
    url: ${DB_URL:r2dbc:postgresql://localhost:5432/tenpodb}
    username: ${DB_USER:root}
    password: ${DB_PASS:root}
    pool:
      enabled: true
      initial-size: 10
      max-size: 20
  data:
    redis:
      host: ${REDIS_URL:localhost}
      port: ${REDIS_PORT:6379}
      timeout: 6000
  kafka:
    bootstrap-servers: ${KAFKA_BROKER:localhost:9092}
    topic:
      history:
        created: com.tenpo.informatic.challenge.history_call
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
      acks: all
    consumer:
      group-id: call-history-group
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      auto-offset-reset: earliest # Empezar a leer desde el inicio si no hay offset previo

  liquibase:
    change-log: classpath:/db/changelog/liquibase.xml
    enabled: true
    url: ${DB_URL_LIQUIBASE:jdbc:postgresql://localhost:5432/tenpodb}
    user: ${DB_USER:root}
    password: ${DB_PASS:root}

management:
  endpoints:
    web:
      exposure:
        include: "*"

wiremock:
  server:
    port: 8881
  stubs:
    path: stubs

percentage:
  service:
    url: http://localhost:8881

logging:
  level:
    org.tenpo.challenge.infrastructure.external: DEBUG

springdoc:
  swagger-ui:
    enabled: true
    path: /swagger-ui.html
  api-docs.path: /v3/api-docs

server:
  port: ${SERVER_PORT:8080}
