services:
  init-kafka:
    image: confluentinc/cp-kafka:7.9.0
    entrypoint: ['/bin/sh', '-c']
    command: |
      "
      kafka-topics --bootstrap-server kafka-broker-1:19092 --list
      
      echo -e 'Eliminanto topics kafka'
      kafka-topics --bootstrap-server kafka-broker-1:19092 --topic com.tenpo.informatic.challenge.history_call --delete --if-exists
      
      echo -e 'Creando topicos de kafka'
      kafka-topics --bootstrap-server kafka-broker-1:19092 --create --if-not-exists --topic com.tenpo.informatic.challenge.history_call --replication-factor 1 --partitions 1
      
      echo -e 'Se han creado los siguientes topicos:'
      kafka-topics --bootstrap-server kafka-broker-1:19092 --list
      "
    networks:
      - tenpo-net